name: Build CI

on:
  push:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "src/main/frontend/yarn.lock"
    
    - name: Install Frontend Dependencies
      run: yarn install --frozen-lockfile 
      working-directory: src/main/frontend
  
  frontent-test:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
    - name: Run Jest Tests
      run: yarn test
      working-directory: src/main/frontend

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Gradle Build
      run: ./gradlew build

  kotlin-test:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      run: ./gradlew test
  
  kotlin-integration-test:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
    - name: Run Integration Tests
      run: ./gradlew integrationTest